feat: added license
defi-wonderland/solidity-foundry-boilerplate pull request #52
Opened 2024-01-17 20:54 UTC by 0xdeo

Closes BES-198

2024-01-18 08:13 UTC, gas1cent requested changes

2024-01-18 08:13 UTC, gas1cent commented on README.md
> +The primary license for Prophet contracts is MIT, see [`LICENSE`](https://github.com/defi-wonderland/solidity-foundry-boilerplate/blob/main/LICENSE)
```suggestion
The primary license for the boilerplate is MIT, see [`LICENSE`](https://github.com/defi-wonderland/solidity-foundry-boilerplate/blob/main/LICENSE)
```

2024-01-19 16:55 UTC, gas1cent approved these changes

2024-01-19 18:17 UTC, 0xRaccoon approved these changes

2024-01-23 10:45 UTC, dristpunk approved these changes

2024-01-23 10:46 UTC, merged