chore: update test workflow
defi-wonderland/solidity-foundry-boilerplate pull request #71
Opened 2024-06-26 16:26 UTC by hexshire

2024-06-26 16:52 UTC, gas1cent approved these changes

2024-06-26 17:28 UTC, 0xteddybear requested changes
while all other github workflows already use checkout action v4, they still use node 18, and here the node version is updated to 20. I'd recommend to use the same node version for all workflows by updating `coverage_check`, `canary` and `release` to 20 as well.

just curious, what prompted this update? was checkoutv3 deprecated? did something break?

2024-06-26 17:31 UTC, hexshire commented
> while all other github workflows already use checkout action v4, they still use node 18, and here the node version is updated to 20. I'd recommend to use the same node version for all workflows by updating `coverage_check`, `canary` and `release` to 20 as well.
> 
> just curious, what prompted this update? was checkoutv3 deprecated? did something break?

I was doing the same on another project that used this boilerplate and I felt like I wanted to update it.

2024-06-26 18:20 UTC, 0xteddybear approved these changes

2024-06-26 18:44 UTC, gas1cent approved these changes

2024-06-26 20:22 UTC, 0xOneTony approved these changes
LGTM! Thank you Hex 😄

2024-06-27 14:44 UTC, drgorillamd approved these changes

2024-06-28 15:39 UTC, merged